# Generated by Django 2.2.6 on 2019-11-16 16:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='friend_id',
            field=models.ManyToManyField(related_name='_user_friend_id_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
