# Generated by Django 2.2.6 on 2019-12-02 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_user_friend_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='friend_id',
        ),
    ]
