# Generated by Django 2.2 on 2020-05-22 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_share'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Share',
        ),
    ]
