# Generated by Django 2.2.6 on 2020-01-24 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_user_friend_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='friend',
            field=models.IntegerField(default=0),
        ),
    ]
