# Generated by Django 2.2.6 on 2020-01-24 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200124_2224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='friend',
        ),
    ]
