# Generated by Django 2.2.6 on 2020-01-25 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_remove_posts_friend'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='is_friend',
            field=models.BooleanField(default=False),
        ),
    ]
