# Generated by Django 2.2.6 on 2020-01-24 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='share',
            name='is_friend',
        ),
        migrations.AddField(
            model_name='friend',
            name='is_friend',
            field=models.BooleanField(default=False),
        ),
    ]
