# Generated by Django 2.2 on 2020-06-25 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friend', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Share',
        ),
    ]
